spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/meeting-planner
    username: meeting_planner
    password: meeting_planner
    platform: postgres
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml