spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/meeting-planner
    username: meeting_planner
    password: meeting_planner
    platform: postgres
    driver-class-name: org.postgresql.Driver
    initialization-mode: never # do not call schema.sql (which reset db)
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml